version: 2.1

jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - run: 'npm i'
      - run: 'test'
workflows:
  build_and_test:
    jobs:
      - build
      - test