version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: build
          command: |
            npm i
      - run:
          name: test
          command: |
            npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
