version: 2.1
orbs:
  slack: circleci/slack@4.2.0
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: build
          command: |
            npm i
      - run:
          name: test
          command: |
            npm test
      - slack/notify:
          channel: heb-updates
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "plain_text",
                    "text": "Vaccines are available! 💉",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Click here to schedule:"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Schedule",
                      "emoji": true
                    },
                    "value": "vaccine",
                    "url": "https://vaccine.heb.com/scheduler",
                    "action_id": "button-action"
                  }
                }
              ]
            }

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
